version: "3.8"

services:
  api-ps-eniqlo-store:
    image: ps-eniqlo-store
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9090:8080
    network_mode: host
    env_file: .env-docker-compose

volumes:
  postgres_data: